try trx test reporting

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -6,8 +6,11 @@ name: .NET
 on:
   push:
     branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+
+permissions:
+  contents: read
+  actions: read
+  checks: write
 
 jobs:
   build:
@@ -23,4 +26,11 @@ jobs:
     - name: Restore dependencies
       run: dotnet restore
     - name: Test
-      run: dotnet test --verbosity normal
+      run: dotnet test --verbosity normal --results-directory TestResults --logger:trx
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: All Tests
+        path: TestResults/**/*.trx
+        reporter: dotnet-trx
